### ISSUE TITLE
LWJGL or other library?

### ISSUE THREAD

**Issue by Mitchellbrine** [PixelatedTacos/Blorpharia#1]
Will we be using a library like LWJGL for Blorpharia? If so, which one?

**Comment by Blorph** [comment]
Perhaps, let's see where the poll takes us.

**Comment by shadowfacts** [comment]
Hmm, which version of LWJGL would we be using? LWJGL 3 has been released and it was a rewrite of LWJGL 2. We could use version 3, but that would mean not have the ability to use any libraries that go on top of LWJGL, e.g. [libGDX](https://libgdx.badlogicgames.com/), which I suggest we use if we go with LWJGL 2.

**Comment by Mitchellbrine** [comment]
I think we should go LWJGL 2, since we can use libGDX. Well, it depends if performance is good with LWJGL 2 and libGDX or plain LWJGL 3.

**Comment by Nucleria** [comment]
I'd say version 2. It has more libraries. Don't care too much though. I don't know much of either one, but I think Gradle, which I've grown to love, is a good idea.

**Comment by Nucleria** [comment]
What's the verdict here?

**Comment by shadowfacts** [comment]
LWJGL 2 and libGDX methinks

**Comment by Mitchellbrine** [comment]
I like that mix.

**Comment by Nucleria** [comment]
Okay.

**Comment by Nucleria** [comment]
Is a Gradle build system okay?

**Comment by Nucleria** [comment]
Also, could I be added to the organization?

**Comment by shadowfacts** [comment]
Yes, I would never use anything else

**Comment by shadowfacts** [comment]
With libGDX you have to use Gradle. 

btw, libGDX has support for desktop and mobile. I recommend using desktop only so we don't have to create multiple UI schemes.

**Comment by Nucleria** [comment]
Okay. Should I set up a workspace or does someone else want to?

**Comment by shadowfacts** [comment]
It's decided, LWJGL 2, libGDX, and Gradle.
